"""
Module: generation.py
Owner: Person A (Signals)
Responsibility: LLM calls, log prob extraction, stochastic sampling, second model call.

Hybrid approach:
- Groq API (llama-3.1-8b-instant) for answer generation and stochastic sampling
- Groq API (gemma2-9b-it) for cross-model disagreement signal
- Local opt-125m for token log probability extraction (Signal 1)
"""

import os
import torch
import numpy as np
from groq import Groq
from transformers import AutoTokenizer, AutoModelForCausalLM
from dotenv import load_dotenv

load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), "../.env"))

groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

PRIMARY_MODEL   = "llama-3.1-8b-instant"
SECONDARY_MODEL = "llama-3.3-70b-versatile"


SYSTEM_PROMPT = (
    "You are a factual question answering assistant. "
    "Answer each question in one short sentence. "
    "Do not explain. Do not hedge. Just answer."
)

SYSTEM_PROMPT_2 = (
    "Answer the following question briefly and directly. "
    "Give only the answer, nothing else."
)

# Local model for log probs (loaded once, reused)
_local_tokenizer = None
_local_model     = None


# ---------------------------------------------------------------------------
# Local model loader
# ---------------------------------------------------------------------------

def _load_local_model():
    global _local_tokenizer, _local_model
    if _local_model is None:
        print("Loading local model for logprobs (facebook/opt-125m)...")
        _local_tokenizer = AutoTokenizer.from_pretrained("facebook/opt-125m")
        _local_model = AutoModelForCausalLM.from_pretrained(
            "facebook/opt-125m",
            dtype=torch.float32,
        )
        _local_model.eval()
        print("Local model loaded.")


# ---------------------------------------------------------------------------
# Model loading (loads local model, no-op for Groq)
# ---------------------------------------------------------------------------

def load_model(model_name: str = None):
    """
    Loads the local opt-125m model for log prob extraction.
    Returns (None, None) to keep interface compatible with pipeline.py.
    """
    _load_local_model()
    print(f"Using Groq API. Primary: {PRIMARY_MODEL}, Secondary: {SECONDARY_MODEL}")
    return None, None


# ---------------------------------------------------------------------------
# Local log prob extraction
# ---------------------------------------------------------------------------

def _get_logprobs_local(question: str, answer_text: str) -> tuple:
    """
    Scores the answer tokens using local opt-125m to get log probabilities.
    The answer was generated by Groq but scored locally for Signal 1.

    Returns (token_logprobs, tokens)
    """
    _load_local_model()

    prompt      = f"Question: {question}\nAnswer: {answer_text}"
    prompt_only = f"Question: {question}\nAnswer:"

    inputs      = _local_tokenizer(prompt,      return_tensors="pt")
    prompt_ids  = _local_tokenizer(prompt_only, return_tensors="pt")
    input_len   = prompt_ids["input_ids"].shape[1]

    with torch.no_grad():
        outputs = _local_model(**inputs)
        logits  = outputs.logits  # (1, seq_len, vocab_size)

    log_probs_all = torch.log_softmax(logits[0], dim=-1)
    input_ids     = inputs["input_ids"][0]

    token_logprobs = []
    tokens         = []

    for i in range(input_len, len(input_ids)):
        token_id = input_ids[i].item()
        lp       = log_probs_all[i - 1, token_id].item()
        token_logprobs.append(lp)
        tokens.append(_local_tokenizer.decode([token_id]))

    return token_logprobs, tokens


# ---------------------------------------------------------------------------
# Core generation: answer + token log probabilities
# ---------------------------------------------------------------------------

def generate_with_logprobs(
    question: str,
    tokenizer=None,
    model=None,
    max_new_tokens: int = 50,
) -> dict:
    """
    Generates answer via Groq, scores tokens locally for log probs.

    Returns dict with keys:
        answer_text     (str)
        token_logprobs  (list of float)
        tokens          (list of str)
    """
    response = groq_client.chat.completions.create(
        model=PRIMARY_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": question},
        ],
        max_tokens=max_new_tokens,
        temperature=0,
    )

    answer_text = response.choices[0].message.content.strip()
    token_logprobs, tokens = _get_logprobs_local(question, answer_text)

    return {
        "answer_text":    answer_text,
        "token_logprobs": token_logprobs,
        "tokens":         tokens,
    }


# ---------------------------------------------------------------------------
# Stochastic sampling: N answers for consistency signal
# ---------------------------------------------------------------------------

def generate_samples(
    question: str,
    tokenizer=None,
    model=None,
    n: int = 10,
    temperature: float = 0.7,
    max_new_tokens: int = 50,
) -> list:
    """
    Generates N stochastic answers via Groq for consistency signal.

    Returns:
        samples (list of str)
    """
    samples = []
    for _ in range(n):
        response = groq_client.chat.completions.create(
            model=PRIMARY_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user",   "content": question},
            ],
            max_tokens=max_new_tokens,
            temperature=temperature,
        )
        samples.append(response.choices[0].message.content.strip())

    return samples


# ---------------------------------------------------------------------------
# Second model answer for disagreement signal
# ---------------------------------------------------------------------------

def generate_model2_answer(
    question: str,
    max_new_tokens: int = 50,
) -> str:
    """
    Calls gemma2-9b-it via Groq with a different system prompt
    to simulate cross-model disagreement signal.

    Returns:
        answer_text (str)
    """
    response = groq_client.chat.completions.create(
        model=SECONDARY_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT_2},
            {"role": "user",   "content": question},
        ],
        max_tokens=max_new_tokens,
        temperature=0,
    )
    return response.choices[0].message.content.strip()


# ---------------------------------------------------------------------------
# Quick test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    TEST_QUESTIONS = [
        "Who wrote the play Hamlet?",
        "What is the capital of France?",
        "What year did the first moon landing occur?",
    ]

    load_model()

    for q in TEST_QUESTIONS:
        print(f"\n{'='*60}")
        print(f"Question: {q}")

        result = generate_with_logprobs(q)
        print(f"Answer:     {result['answer_text']}")
        print(f"Tokens:     {result['tokens']}")
        print(f"Log probs:  {[round(lp, 3) for lp in result['token_logprobs']]}")
        print(f"Mean logp:  {round(np.mean(result['token_logprobs']), 3)}")

        model2 = generate_model2_answer(q)
        print(f"Model 2:    {model2}")

        samples = generate_samples(q, n=3)
        print(f"Samples:    {samples}")